### ISSUE TITLE
What is the correct xmlrpc endpoint?

### ISSUE THREAD

**Issue by psycholyzern** [jbfriedrich/ghost2wp#1]
I tried `/wp-json/v2/posts` and got `401 Unauthorized` error even I already specified `-u` and `-p` with my username and password respectively.

**Comment by jbfriedrich** [comment]
Hey @psycholyzern, from the [Wordpress Codex](https://codex.wordpress.org/XML-RPC_Support):

> * If your WordPress root is http://example.com/wordpress/, then you have:
>   * Server: http://example.com/ (some tools need just the 'example.com' hostname part)
>   * Path: /wordpress/xmlrpc.php
>   * complete URL (just in case): http://example.com/wordpress/xmlrpc.php

Hope that helps!

**Comment by psycholyzern** [comment]
I Googled too but it keep giving me result about WP REST API and it mislead me.
Thanks a lot!
